elasticsearch:
  replicas: 1
  image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
  es_java_opt: -Xmx1g -Xms1g
  sysctlVmMaxMapCount: "262144"
  clusterHealthCheckParams: "wait_for_status=green&timeout=1s"
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  persistence:
    storageClassName:
    storageSize: 100Gi

kibana:
  replicas: 1
  image: docker.elastic.co/kibana/kibana:7.17.14
  password: elastic
  init_index_pattern: false
  ingress:
    ingressClassName: nginx
    host: kibana.example.com
    annotations: {}
    tls:
      secret: kibana-tls
      issuer: letsencrypt-prod

fluentd:
  image: fluent/fluentd-kubernetes-daemonset:v1.16-debian-elasticsearch7-1
  enabled: false

filebeat:
  image: docker.elastic.co/beats/filebeat:7.17.14
  enabled: true
  updateStrategy: RollingUpdate
  config:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        exclude_files:
          - /var/log/containers/fluent.*
          - /var/log/containers/es-cluster-.*
          - /var/log/containers/kube-proxy.*
          - /var/log/containers/konnectivity-agent.*
          - /var/log/containers/efs-csi-node-.*
          - /var/log/containers/ebs-snapshot-controller-.*
          - /var/log/containers/gke-.*
          - /var/log/containers/event-exporter-gke-.*
          - /var/log/containers/calico-.*
          - /var/log/containers/kube-dns-.*
          - /var/log/containers/netd-.*
          - /var/log/containers/pdcsi-node-.*
          - /var/log/containers/csi-azuredisk-node-.*
          - /var/log/containers/cloud-node-manager-.*
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      output.elasticsearch:
        protocol: https
        hosts: ['${ELASTICSEARCH_HOST:logs-elasticsearch}:${ELASTICSEARCH_PORT:9200}']
        username: "${ELASTICSEARCH_USERNAME:elastic}"
        password: "${ELASTICSEARCH_PASSWORD}"
        ssl:
          verification_mode: none
          certificate_authorities:
          - /usr/share/filebeat/config/certs/ca.crt
          - /usr/share/filebeat/config/certs/tls.crt

curator:
  schedule: "0 1 * * *"
  image: "public.ecr.aws/bitnami/elasticsearch-curator:5.8.4-debian-11-r11"
  unit_count: 15
  unit: days
  timestring: '%Y.%m.%d'
