elasticsearch:
  replicas: 1
  image: docker.elastic.co/elasticsearch/elasticsearch:7.17.26@sha256:1685e7e91b123a825a3b01cf577b0f7836e062e9cb24a1b5e76be76dd29127ea
  es_java_opt: -Xmx1g -Xms1g
  sysctlVmMaxMapCount: "262144"
  clusterHealthCheckParams: "wait_for_status=green&timeout=1s"
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  persistence:
    storageClassName:
    storageSize: 100Gi

kibana:
  replicas: 1
  image: docker.elastic.co/kibana/kibana:7.17.26@sha256:ff1fe238c68c1c8a30dd924b5d1556af14d53caa9e35e8dc1d8544bdf34881ee
  password: elastic
  init_index_pattern: false
  ingress:
    ingressClassName: nginx
    host: kibana.example.com
    annotations: {}
    tls:
      secret: kibana-tls
      issuer: letsencrypt-prod

fluentd:
  image: fluent/fluentd-kubernetes-daemonset:v1.18-debian-elasticsearch7-1@sha256:3990f1579ac3f40ab8514e3643fe0b30a1df2947d6e486047bb1926add0ee20d
  enabled: false

filebeat:
  image: docker.elastic.co/beats/filebeat:7.17.26@sha256:16bdd7222184b0f1945386b7325ac058ce6e933047cd99c85e2bd393a403f4a9
  enabled: true
  updateStrategy: RollingUpdate
  config:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        exclude_files:
          - /var/log/containers/fluent.*
          - /var/log/containers/es-cluster-.*
          - /var/log/containers/kube-proxy.*
          - /var/log/containers/konnectivity-agent.*
          - /var/log/containers/efs-csi-node-.*
          - /var/log/containers/ebs-snapshot-controller-.*
          - /var/log/containers/gke-.*
          - /var/log/containers/event-exporter-gke-.*
          - /var/log/containers/calico-.*
          - /var/log/containers/kube-dns-.*
          - /var/log/containers/netd-.*
          - /var/log/containers/pdcsi-node-.*
          - /var/log/containers/csi-azuredisk-node-.*
          - /var/log/containers/cloud-node-manager-.*
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      output.elasticsearch:
        protocol: https
        hosts: ['${ELASTICSEARCH_HOST:logs-elasticsearch}:${ELASTICSEARCH_PORT:9200}']
        username: "${ELASTICSEARCH_USERNAME:elastic}"
        password: "${ELASTICSEARCH_PASSWORD}"
        ssl:
          verification_mode: none
          certificate_authorities:
          - /usr/share/filebeat/config/certs/ca.crt
          - /usr/share/filebeat/config/certs/tls.crt

curator:
  schedule: "0 1 * * *"
  image: "public.ecr.aws/bitnami/elasticsearch-curator:5.8.4-debian-11-r11@sha256:46c98206dfaef81705d9397bd3d962d1505c8cfe9437f86ea0258d5cbef89e7f"
  unit_count: 15
  unit: days
  timestring: '%Y.%m.%d'
