{{- if .Values.filebeat.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    app: filebeat
    app.kubernetes.io/name: filebeat
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $path, $config := .Values.filebeat.config }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}

{{- end -}}
