{{- if .Values.filebeat.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    app: filebeat
    app.kubernetes.io/name: filebeat
    {{- include "efk.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.filebeat.config }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}

{{- end -}}
