
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logreader
  labels:
    app: logreader
    app.kubernetes.io/name: logreader
    {{- include "efk.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logreader
  labels:
    app.kubernetes.io/name: logreader
    {{- include "efk.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logreader
  labels:
    app.kubernetes.io/name: logreader
    {{- include "efk.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: logreader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: logreader
  namespace: {{ .Release.Namespace }}
