
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logreader
  labels:
    app: logreader
    app.kubernetes.io/name: logreader
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logreader
  labels:
    app: logreader
    app.kubernetes.io/name: logreader
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logreader
roleRef:
  kind: ClusterRole
  name: logreader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: logreader
  namespace: {{ .Release.Namespace }}
