name: helm-docs
on:
  pull_request:
    paths:
      - "charts/**/values.yaml"
      - "charts/**/Chart.yaml"


permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chart-docs:
    runs-on: ubuntu-latest
    steps:

      - name: Get helm-docs
        run: |
            URL="https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz"
            wget -qO - $URL | tar -xzvf - -C /usr/local/bin helm-docs
            helm-docs --version

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Run helm-docs
        run: |
          helm-docs --log-level warning --template-files ./ci/README.md.gotmpl
          git status
          if [[ $(git status --porcelain) ]]; then
            echo "Changes"
            git config user.name "helm-docs"
            git config user.email "helm-docs@datarobot.com"
            git add . && git commit -am "[bot] Update README.md with helm-docs" --signoff && git push
          else
            echo "No changes"
          fi
