name: Helm conftest
on: [pull_request]
jobs:
  check-charts:
    name: Run conftest for all charts
    runs-on: ubuntu-latest
    container:
      image: alpine/helm:latest@sha256:5347496fd48169d4b12f7f1c1a02ecc57c895223b9e732fe15e23926a2f10648
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Dependencies
        run: apk add --no-cache curl tar

      - name: Install Conftest
        run: |
          curl -sSL https://github.com/open-policy-agent/conftest/releases/download/v0.55.0/conftest_0.55.0_Linux_x86_64.tar.gz -o conftest.tar.gz
          tar -xzvf conftest.tar.gz -C /usr/local/bin/
          chmod +x /usr/local/bin/conftest
          rm conftest.tar.gz

      - name: Validate all charts
        run: bash ci/helm-conftest.sh
