name: Helm conftest
on: [pull_request]
jobs:
  check-charts:
    name: Run conftest for all charts
    runs-on: ubuntu-latest
    container:
      image: alpine/helm:latest@sha256:2174b15dcd4159888dae175b5f033583f903cbc39b16711c95e83021a79cfd21
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Dependencies
        run: apk add --no-cache curl tar

      - name: Install Conftest
        run: |
          curl -sSL https://github.com/open-policy-agent/conftest/releases/download/v0.55.0/conftest_0.55.0_Linux_x86_64.tar.gz -o conftest.tar.gz
          tar -xzvf conftest.tar.gz -C /usr/local/bin/
          chmod +x /usr/local/bin/conftest
          rm conftest.tar.gz

      - name: Validate all charts
        run: bash ci/helm-conftest.sh
