name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '42 * * * 0'
  push:
    branches:
    - master
    paths:
    - renovate.json

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Renovate
        uses: renovatebot/github-action@v41.0.3
        with:
          renovate-version: 39.7.5 # renovate: ghcr.io/renovatebot/renovate
        env:
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: "[\"bump-chart-version.sh\"]"
          RENOVATE_CONFIG_FILE: renovate.json
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
