name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '42 * * * 0'
  push:
    branches:
    - master
    paths:
    - renovate.json
    - .github/workflows/renovate.yaml


jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Get helm-docs
        run: |
            URL="https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz"
            wget -qO - $URL | tar -xzvf - -C /usr/local/bin helm-docs
            helm-docs --version


      - name: Renovate
        uses: renovatebot/github-action@248bf5a619694187930adc80b9343c37761c173f # v43.0.1
        with:
          renovate-version: 39.7.5 # renovate: ghcr.io/renovatebot/renovate
        env:
          RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: "[\"bump-chart-version.sh\"]"
          RENOVATE_CONFIG_FILE: renovate.json
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
